[package]
name = "sync-doc"
version = "0.1.0"
authors = ["frozenlib <frozenlib@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
ignore = "0.4.17"
anyhow = "1.0.39"
regex = "1.4.5"
parse-display = "0.4.1"