[package]
name = "include-doc"
version = "0.1.1"
authors = ["frozenlib <frozenlib@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
ignore = "0.4.18"
anyhow = "1.0.44"
regex = "1.5.4"
parse-display = "0.5.3"
colored = "2.0.0"
once_cell = "1.8.0"
thiserror = "1.0.30"
